[package]
name = "wain-validate"
version = "0.1.5"
authors = ["rhysd <lin90162@yahoo.co.jp>"]
edition = "2021"
description = "WebAssembly syntax tree validator for wain project"
license = "MIT"
homepage = "https://github.com/rhysd/wain/tree/master/wain-validate"
repository = "https://github.com/rhysd/wain"
readme = "README.md"
include = ["src/**/*.rs", "Cargo.toml", "README.md"]
keywords = ["wasm", "webassembly", "validator"]
categories = ["wasm"]

[package.metadata.release]
pre-release-commit-message = "release {{crate_name}} {{version}}"
consolidate-commits = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wain-ast = { path = "../wain-ast", version = "0.2" }
std = { path = "../../std" }
core = { path = "../../core" }

[badges]
maintenance = { status = "actively-developed" }
